### ISSUE TITLE
Tech Session 1: An Overview of Bisq

### ISSUE THREAD

**Issue by cbeams** [bisq-network/events#1]
_As this is our first tech session, a bit of context:_

_Somewhat like the growth calls we've done recently, these "tech sessions" will be regular or semi-regular YouTube live streams open to anyone and covering technical topics like Bisq's P2P network._

_Aside from documenting important technical details about Bisq, a major goal of these calls is to attract developers who might be interested in contributing to come find out about how everything works, ask questions and see where they might like to get involved._

Fittingly, this first session will be a high-level technical overview of Bisq. We'll lay out the component parts of the Bisq desktop client and network, such that developers new and old can build a shared mental model that we can build on and extend in future, more focused tech sessions.

## Prep

- [x] @cbeams: Set a date and add it to the https://bisq.network/events calendar
- [x] @cbeams: Set up live stream
- [x] @cbeams: Announce via @bisq_network
- ~~@cbeams: Announce via the Bisq Newsletter (?)~~
- [x] @ManfredKarrer to prepare a deck
- [x] @cbeams to add slides to deck on collaboration and compensation under the Bisq DAO

## Follow-up

 - [ ] Do a poll (probably in Slack, possibly on Twitter) about which topic(s) people want to see next
 - [ ] Create issues for each

**Comment by cbeams** [comment]
This event has been added to https://bisq.network/calendar and the live stream is ready to go at https://youtu.be/ulmUVh3XjRg.

**Comment by ManfredKarrer** [comment]
Presentation is here: https://docs.google.com/presentation/d/1Rihu9skoGhlQ5vHvt_1s-ClQlbBxpaKcOX10_pQcnD0/edit?ts=5a98aa4d#slide=id.g3128f3a372_0_57

**Comment by blabno** [comment]
Would be nice if you could include in your presentation what is "base currency" in context of Bisq, how to run different base currencies and how it relates to transaction fees and saving wallet

**Comment by cbeams** [comment]
I just announced the session via Twitter at https://twitter.com/bisq_network/status/969710536115015681.

**Comment by cbeams** [comment]
> Would be nice if you could include in your presentation what is "base currency" in context of Bisq, how to run different base currencies and how it relates to transaction fees and saving wallet

Might be better for a more detailed session later, but like I think Manfred mentioned in Slack, this could be good for Q&A afterward.

**Comment by cbeams** [comment]
Closing as complete, just realized this was still open.
