### ISSUE TITLE
Bitcoin Cambodia Meetup (Phnom Penh)

### ISSUE THREAD

**Issue by csacher** [bisq-network/events#13]
Will be talking about Bisq at the local Bitcoin Cambodia Meetup in Phnom Penh in order to gain insight about Cambodian reality.

**Comment by csacher** [comment]
Bitcoin Cambodia is organized bi-weekly at Coin Cafe in Phnom Penh. 
https://www.meetup.com/de-DE/Phnum-Penh-Bitcoin-Meetup/
In total 12 people attended the meetup. 

Here are my insights from the event:

1. Many people are interested in actual buying and selling crypto assets and gaining profits through increasing prices. Less interest in any philosophical or ideological discussion. Many people blindly put any money they have in scamcoins or anyone who promises big returns. Therefore lots of people end up losing their investment, which scares others away.

2. Very few are educated about the buying and selling process of crypto and those who are (mostly westerners) provide some kind of broker service for locals (eg. www.mekongmonkey.com).

3. Government does not directly ban or regulated crypto but has been repeatedly recommending staying away from any involvement and bank transfers. 

4. One major money transfer that is used in Cambodia is "WING". Which is some kind of mobile payment (one goes to one of the many offices/stores and transfers the money to another person by providing the recipients mobile phone number). The sender and receiver gets a paper receipt. No online tracking possible. 

5. As financial education is low and people hardly know about crypto, few people actually show interest in a decentralized, private and secure exchange. They would much rather go for a third party handling all of their transactions. 

Will continue reaching out to other folks in the Facebook Group (Bitcoin Cambodia) to look out for any broader application of Bisq in Cambodia for this moment in time.

**Comment by cbeams** [comment]
Thanks for the write-up, @csacher!
