### ISSUE TITLE
Bisq on The Coin Pod

### ISSUE THREAD

**Issue by cbeams** [bisq-network/events#19]
I recorded an interview yesterday with Zack Voell for a episode of The Coin Pod that should be released on Tuesday March 13th.

https://twitter.com/thecoinpod

**Comment by zackvoell** [comment]
Thanks for coming on the podcast, Chris! Links to the episode are at: https://twitter.com/thecoinpod

**Comment by cbeams** [comment]
Closing as complete. Thanks again @zackvoell. From https://twitter.com/thecoinpod/status/973599613088403456:

![image](https://user-images.githubusercontent.com/301810/37396472-444037e6-2779-11e8-9040-967f38158aa7.png)
