### ISSUE TITLE
Dev Call "Seed nodes: Goals and strategies on how to get seed nodes more stable and reliable"

### ISSUE THREAD

**Issue by freimair** [bisq-network/events#27]
# Agenda
- [x] Dev resources or "Why nobody reacts to stuff"
  - *responses on slack have been slow, new devs seemed a bit lost*
  - *currently 3 developers able to merge stuff into master, one of them is on holiday, another one is moving house -> reviewing and merging is slow (Manfred partially "unretired" to help out)*
  - *there have been about 5 senior full-time devs working on bisq just a few weeks ago*
  - *things are expected to speed up again in a couple of weeks*
  - *the onboarding discussion has been added to the topic queue*
- [x] Seednodes: Goals and strategies on how to get seednodes more stable and reliable *16:00*
  - Sync: what is a seed node and what is it good for
    - *basically recite https://docs.bisq.network/exchange/howto/run-seednode.html#what-is-a-bisq-seed-node and do some drawings*
    - *sync on startup, no sync during runtime*
    - *use the monitor to discuss messages and synchronization issues*
    - *wiz suggested another monitoring tool (nagios, discussion "schedule") (35:00)*
    - *the DAO cannot work without seed nodes, because standard nodes are no dao full nodes (39:00)*
       - *wiz suggested to offer an incentive (discount on transaction fees) for people to run full nodes*
       - *we are not sure if that is a good idea because*
          - *open attack surface*
          - *not feasible until the software is more stable*
  - Situation:
    - stuff goes out of sync
       - *why stuff goes out of sync (52:00)*
       - *discuss how to sync the seed nodes*
       - *wiz: just connect the seed nodes with dedicated connections*
         - *does that solve the DAO sync as well? check!*
         - *PGP had similar issues back then (59:00)*
       - *discussion on DoS and countermeasures(1:00:30)*
    - collectd does not like the EOL openjdk10
  - Info: countermeasures in progress
    - use daily restart (Info: Manfreds branch vs. master vs. https://github.com/bisq-network/bisq/tree/seednode_temporaryfix) *(55:00)*
    - host monitoring (upcoming) *1:05:00*
      - *why we are not monitoring our seed nodes yet*
      - *create incentive: not accept compensation requests*
    - working on a scheduled sync without restart
  - Decide: Strategy. the draft strategy which we already follow is: *1:15:00*
    - create/use special seed-node branch with manfreds restart option
    - for as long as it takes for the scheduled resync during runtime to be ready
    - find out what causes the out-of-sync stuff in the DAO state hashes and what keeps them out of sync
    - *Suggestion: add a test suit for seed nodes resulting in good/fail*
    - *Suggestion: move to docker containers, so we can assess the software version a seed node is (miker offered to provide a docker config)*
    - *Suggestion: tweak the Bisq code for catching up on DAO blocks https://github.com/bisq-network/bisq/issues/3094*
  - next steps
    - get the monitoring of the seed nodes up and running

# Schedule
When: 2019-08-15 10:00 AM CEST
Duration: 1,5h
How: https://zoom.us/j/356047586, web link https://zoom.us/wc/join/356047586?pwd=

# Meeting minutes
see above inline
https://www.youtube.com/watch?v=Ystni2F5onk

**Comment by m52go** [comment]
I might join. With respect to the first item (developer resources), could we discuss strategies for attracting more developers to the project? I've been thinking of some approaches, but would be helpful to get feedback from actual developers.

**Comment by ghubstan** [comment]
The meeting time listed above is 2019-08-15 10:00 AM CEST.  That would be 5:00 a.m. my time (Sao Paulo, BR).

I have contributed little so far, so it's not worth changing your schedule for me.  I've also missed many other online meetings scheduled at convenient times for me, but they always occur while I have to be elsewhere.

Sorry I'm not attending.  It's not because I don't want to.

**Comment by devinbileck** [comment]
I will be unable to attend at 10:00 AM CEST but am fine just reviewing meeting minutes afterwards.

**Comment by ManfredKarrer** [comment]
@ghubstan @devinbileck Please post possible time slots. We have now devs in vetry different timezones (Europe, Japan, Canada, Brazil) so might be hard to find an overlap but would be good is possible.

**Comment by ghubstan** [comment]
@ManfredKarrer @devinbileck @m52go Mondays and Thursdays won't work for me, but the other five days of the week are fine.  I'm in the BRT timezone, 5 hours behind Central European Time.

Anytime after 1:30 p.m. CEST on Tue, Wed, Fri, Sat, Sun works for me.

**Comment by devinbileck** [comment]
For tomorrow, I am available 6:00 PM CEST to 12:00 AM CEST.
Generally I am always available Mon-Fri 6:00 PM CEST to 8:00 PM CEST, but can sometimes be available other times after 8:00 PM CEST.

**Comment by ghost** [comment]
Hello,
Would Munin be of use for the monitoring ?
https://en.wikipedia.org/wiki/Munin_(software)

**Comment by ManfredKarrer** [comment]
FYI: https://github.com/bisq-network/bisq/issues/3094

**Comment by m52go** [comment]
Recording is [here](https://youtu.be/Ystni2F5onk).
