### ISSUE TITLE
Dev-Call "What's next"

### ISSUE THREAD

**Issue by freimair** [bisq-network/events#33]
- [x] new trade protocol
  - [x] Trader Chat
  - [x] Mediation vs. Arbitration
- [x] Bisq v2
  - [x] another new trade protocol, this time off-chain

I decided that the dev-call is a very efficient presentation of the points of the agenda and definitely worth listening to. Together with @chimp1984 comment below, the detailed information is made accessible as well.

# Recording
https://youtu.be/YnTA3p-5v00

**Comment by chimp1984** [comment]
There are 2 new trade protocols in consideration:
- The "new trade protocol" (NTP) based on 2of2 Multisig deposit tx, trader chat, mediation and as last step a delayed payout to either 2of3 Multisig with arbitration or to the Bisq donation address and reimbursement request to the Bisq DAO (maker can choose which option to use).
- The "off-chain trade protocol" (OCTP) which separates trade protocol and security protocol. It is based on BSQ bonds which can be re-used for multiple trades over long time (similar to Lightning channels). The trade is completely decoupled from any crypto currency which enables lots of fundemantal improvements (no privacy leaks due on-chain tx linking, instant trades, no integrated wallet required, no need that maker need to be online,...).

Links to new trade protocol: 
https://github.com/bisq-network/proposals/issues/52
I started to work on the new trade protocol as defined here:
https://docs.google.com/document/d/1Ni4EBb8iOTFH7Tx9BRB6K3qHMEGt47BFyE79Xb7IkVk
Here was an older roadmap doc (not 100% up to date): https://docs.google.com/document/d/160-74pYDowU4ok3czx-hG6QZYiH0tpNdUN-J4xIdVgI/

Links to off-chain trade protocol: https://github.com/bisq-network/proposals/issues/118
https://docs.google.com/document/d/1sTbm7SuIGQ5HWCwbxYfnklyMHB_-jIr7kAM9-ZSzzH8

Both protocols will require a hard fork or we deploy it as a new application in parallel to the existing old version.

**Comment by m52go** [comment]
Recording published here:
https://youtu.be/YnTA3p-5v00
