### ISSUE TITLE
FOSDEM 2018 in Brussels, Belgium

### ISSUE THREAD

**Issue by cbeams** [bisq-network/events#9]
FOSDEM is a potentially target-rich environment for the kind of developers we're looking to work on Bisq. My understanding (I've never attended) is that it tends to be a more professional crowd, but still one focused keenly on FOSS.

I do not know how prevalent Bitcoiners are at FOSDEM, but I have a hunch that with thousands of FOSS developers in attendance, a non-zero number of them will fit the following profile:

 - currently employed, experienced JVM developer;
 - having experience with and deep interest in Bitcoin as a user/holder;
 - may or may not have done any Bitcoin development work, but would like to;
 - and is, because of their holdings, now considering leaving their job to work in and for crypto 

This profile is what we want to seek out anywhere and everywhere, but FOSDEM is probably a particularly good place to find them.

@mrosseel will be in attendance this year, and per https://github.com/bisq-network/dao/issues/24#issuecomment-356207225, he has offered the following:

> if no-one can make it to FOSDEM 2018, I can tape one/more A4 with a recruitment message.

![image](https://user-images.githubusercontent.com/301810/34882419-cbcd4f98-f7b6-11e7-8004-5ccf260fe8f2.png)

To make this effective, we need to:

 - [x] Reach out via Twitter to see who else is going to FOSDEM that could help represent Bisq ([Tweet](https://twitter.com/bisq_network/status/952150022279368707))
 - [x] Design a flyer that @mrosseel and other ambassadors can distribute (@mrosseel did this, thanks!)
 - ~~Produce some swag (especially stickers) and get them to @mrosseel and other ambassadors~~

We should also see if it's possible to do an informal 1-minute announcement in one or more of the Java-related rooms, ideally early on in the conference, and preferably multiple times throughout it, letting folks know the team from Bisq is at the conference, who we are, what we do, and that we're looking to talk with JVM / Bitcoin / P2P network devs, etc.

Please add comments here with any other ideas and feedback about how we should approach this event.

**Comment by cbeams** [comment]
@mrosseel and Neiman (@neiman30?) will both be at FOSDEM, and have agreed to help promote Bisq, but unfortunately we did not get together any sort of flyer or swag in time for them to distribute.

Mike, Neiman, anything you can do in the meantime to raise awareness about what we're up to is really appreciated! You guys know the conference better than me (I've never been), so I'll leave it to you, but like I mentioned in the description above, perhaps there could be opportunities in some of the Java-oriented rooms to make announcements about projects, etc. That might be a good way of getting the word out, letting folks know how to get hold of you during the conference to talk more, etc.

Let me know here or via Slack if there's any support I can provide during the weekend, questions I can answer, etc. Thanks and good luck!

**Comment by cbeams** [comment]
@mrosseel, could you give a brief recap of what happened at FOSDEM? Any prospects, interest from folks, etc? Anything you think would be valuable to share, thanks.

**Comment by mrosseel** [comment]
* bisq ad was up in the job corner the entire weekend
* there was a blockchain BOF session where everyone presented their project etc, there I told about bisq and called for devs to join - one guy approached me afterwards, I've since mailed him to followup, will see what comes out of it.
* there will probably be a blockchain devroom next year, I'll monitor that so we can get a talk in

**Comment by cbeams** [comment]
Closing as complete. Thanks for the update, @mrosseel, and for everything you did there.
